### ISSUE TITLE
Package set needs subversion dependency 

### ISSUE THREAD

**Issue by dbcesar** [Brazilian-Institute-of-Robotics/bir.flat_fish-package_set#32]
I've just installed rock on a fresh Ubuntu 16.04 and rock is still not installing `subversion`, even after the last @romulogcerqueira's commit. So the component control/visp breaks on the `aup` phase.

**Comment by dbcesar** [comment]
Actually, I think this should be included in the rock package set.

This PR may fix it. 
https://github.com/rock-core/rock-package_set/pull/131

**Comment by doudou** [comment]
I just did a bootstrap on a clean 16.04, and checked out control/visp. It worked like a charm.

**Comment by doudou** [comment]
Could you run `autoproj show control/visp` in your workspace ?

**Comment by doudou** [comment]
Note: it will probably not do what you expect if you try `amake control/visp` before running `aup control/visp` ...

**Comment by doudou** [comment]
Yep. `aup control/visp` works, `amake control/visp` does not. What is Romulos' commit you were talking about ?

**Comment by dbcesar** [comment]
> It worked like a charm.

Just for your information. I'm running on sdformat4/gazebo7 branchs.

> Could you run autoproj show control/visp in your workspace ?

```
diego@44d69573fb7c:~/dev.bir$ autoproj show control/visp
source package control/visp
  source definition
    type: svn
    url: svn://scm.gforge.inria.fr/svnroot/visp/trunk/ViSP
    patches: ["/home/diego/dev.bir/autoproj/remotes/rock/patches/visp.patch"]
    first match: in rock
      branch: $ROCK_BRANCH
      github: rock-control/control-$PACKAGE_BASENAME
    overriden in rock
      type: svn
      url: svn://scm.gforge.inria.fr/svnroot/visp/trunk/ViSP
      patches: ["$AUTOPROJ_SOURCE_DIR/patches/visp.patch"]
  is not directly selected by the manifest
  direct reverse dependencies: control/orogen/visp
  recursive reverse dependencies: control/orogen/visp
  selected by way of
    bir.flat_fish.br>control/orogen/visp>control/visp
  directly depends on: base/cmake, base/types
  optionally depends on: 
  dependencies on OS packages: cmake
```

> What is Romulos' commit you were talking about ?

`https://github.com/Brazilian-Institute-of-Robotics/bir.flat_fish-package_set/commit/f9a11674e7ca97af7a639ad038fd385d2a86078d`
This commit was done in order to fix this problem.

**Comment by doudou** [comment]
Have you seen my comment about `aup` vs `amake` ?

**Comment by dbcesar** [comment]
> Have you seen my comment about aup vs amake ?

In my particular case, the problem happened when I run `aup` on the very first time in order to download all packages.

**Comment by doudou** [comment]
Which autoproj version ? Where did you get the bootstrap ?

**Comment by dbcesar** [comment]
> Where did you get the bootstrap ?

`wget http://www.rock-robotics.org/master/autoproj_bootstrap` 
and then
`~/.rbenv/versions/2.3.1/bin/ruby autoproj_bootstrap git git@github.com:Brazilian-Institute-of-Robotics/bir.flat_fish.br-buildconf.git`

**Comment by doudou** [comment]
Yep. Found the bug on the autoproj side
